
services:
  postgres:
    image: postgres:17
    container_name: micro-service-db
    restart: always
    environment:
      POSTGRES_USER: some
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: micro_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: micro-service-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://138.124.35.157:5432/micro-db
      SPRING_DATASOURCE_USERNAME: some
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_FLYWAY_ENABLED: true
      JWT_SECRET: ${JWT_SECRET}
      JWT_ACCESS-TTL-HOURS: 1
      JWT_REFRESH-TTL-DAYS: 3


volumes:
  postgres_data: